 console.log("iam external")
// document.write("hello")
// document.write(20)
// document.writeln("hi")
// document.write("bye")
alert("welcome to my webpage")

document.writeln(1-'1')
document.writeln(1/2)
document.writeln(1/"hi")
document.writeln(1+"1")
document.writeln(1+1)
document.writeln(1+10-10+12*2+"1"-2)
document.writeln(1/10)
document.writeln(1/0)
document.write(1+20*2-2/4+(4+3)+(3/6)*5+1*0+1+3)